[project]
name = "dataengineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.37",
    "duckdb>=1.4.3",
    "jupyterlab>=4.5.3",
    "pandas>=2.3.3",
    "pyspark>=4.1.1",
    "requests>=2.32.5",
]
